version: '3.8'

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "9000:8000"
    environment:
      - SUPABASE_URL=http://host.docker.internal:54321
      - SUPABASE_KEY=${SUPABASE_KEY}
      - REDIS_URL=redis://redis:6379/0
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - redis
    volumes:
      - ./backend/app:/app/app
    networks:
      - scraping-network

  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: celery -A app.worker.celery worker --loglevel=info
    environment:
      - SUPABASE_URL=http://host.docker.internal:54321
      - SUPABASE_KEY=${SUPABASE_KEY}
      - REDIS_URL=redis://redis:6379/0
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - redis
    volumes:
      - ./backend/app:/app/app
    networks:
      - scraping-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - scraping-network
    volumes:
      - redis-data:/data

networks:
  scraping-network:
    driver: bridge

volumes:
  redis-data: 