name: Backend CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          
      - name: Update dependencies
        run: |
          # Force regenerate the lock file
          rm -f poetry.lock
          poetry lock
          # Install dependencies
          poetry install --without dev --no-root
        working-directory: backend
        
      - name: Install development tools
        run: pip install flake8 pytest
        working-directory: backend
        
      - name: Lint
        run: poetry run flake8
        working-directory: backend
        
      - name: Test
        run: poetry run pytest --maxfail=1 --disable-warnings -q
        working-directory: backend
        
      - name: Build Docker image
        if: github.ref == 'refs/heads/main'
        run: docker build -t ghcr.io/${{ github.repository }}/scraping-wizard-api:latest ./backend
        
      - name: Log in to GitHub Container Registry
        if: github.ref == 'refs/heads/main'
        run: echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        
      - name: Push Docker image
        if: github.ref == 'refs/heads/main'
        run: docker push ghcr.io/${{ github.repository }}/scraping-wizard-api:latest 