name: Backend CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          
      - name: Install dependencies
        run: poetry install --without dev --no-root
        working-directory: backend
        
      - name: Lint
        run: poetry run flake8
        working-directory: backend
        
      - name: Test
        run: poetry run pytest --maxfail=1 --disable-warnings -q
        working-directory: backend
        env:
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          ENVIRONMENT: 'test'
        
      - name: Build Docker image
        if: github.ref == 'refs/heads/main'
        run: |
          # Add build args for Sentry
          docker build \
            --build-arg SENTRY_DSN=${{ secrets.SENTRY_DSN }} \
            --build-arg ENVIRONMENT=production \
            -t ghcr.io/${{ github.repository }}/scraping-wizard-api:latest ./backend
        
      - name: Log in to GitHub Container Registry
        if: github.ref == 'refs/heads/main'
        run: echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        
      - name: Push Docker image
        if: github.ref == 'refs/heads/main'
        run: docker push ghcr.io/${{ github.repository }}/scraping-wizard-api:latest
        
      - name: Deploy to AWS ECS
        if: github.ref == 'refs/heads/main'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          aws ecs update-service \
            --cluster ${{ secrets.ECS_CLUSTER }} \
            --service ${{ secrets.ECS_SERVICE }} \
            --force-new-deployment 