name: Python Linting

on:
  push:
    paths:
      - '**.py'
  pull_request:
    paths:
      - '**.py'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 autopep8
          
      - name: Run linting
        run: |
          # Run flake8 on all Python files
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          
          # Run with all checks but as warning only
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics 